---
abstract: 'convert between RDF and vCard'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - Contacts
  - Directory
  - RDF
  - SemWeb
  - 'Semantic Web'
  - XML
  - hCard
  - vCard
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::vCard
name: RDF-vCard
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  RDF::Trine: 0.135
  RDF::TrineX::Functions: 0
  Text::vFile::asData: 0.07
  URI: 0
  XML::LibXML: 1.70
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-vCard
  homepage: https://metacpan.org/release/RDF-vCard
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-vcard
version: 0.010
