# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#>.

<http://purl.org/NET/cpan-uri/dist/RDF-vCard/project>
	:perl_version_from
		_:main;
	:version_from
		_:main;
	:readme_from
		_:main;
	:install_script
		_:vcard2rdf,
		_:vcard2xml;
	:test_requires
		"Test::More 0.61";
	:requires
		"XML::LibXML 1.70",
		"namespace::clean",
		"RDF::Trine 0.135",
		"RDF::TrineX::Functions",
		"Text::vFile::asData 0.07",
		"URI".

_:main
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>
		"lib/RDF/vCard.pm".

_:vcard2rdf
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>
		"bin/vcard2rdf".

_:vcard2xml
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>
		"bin/vcard2xml".
